name: napari-env

channels:
  - conda-forge

dependencies:
  - python=3.10
  - napari=0.4.*
  - pyqt=5.15.*
  - qt-main
  - numpy
  - scipy
  - scikit-image
  - tifffile
  - imageio
  - imageio-ffmpeg
  - h5py
  - caiman
  - dask
  - vispy
  - pyopengl
  - pandas
  - matplotlib
  - pillow
  - statsmodels
  - pip
